version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: erb-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: roor
      MYSQL_DATABASE: erb-system
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proor"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    external: true
    name: 9c01b1618c688906acc9b40d8185b60b543316d4fe3fe07d48b020fa02fdf607
